name: Build and publish Docker image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Ensure repo slug is always lowercase and export as env var
      - name: Set lowercased repo slug
        run: echo "REPO_SLUG=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Compose tags for Docker (always lowercase)
      - name: Set Docker tags
        run: |
          echo "TAGS=ghcr.io/${REPO_SLUG}:${{ github.ref_name }},ghcr.io/${REPO_SLUG}:latest" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.TAGS }}
